version: '3'
services:
  mongo:
    image: mongo:4
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    restart: always
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
volumes:
  mongodata: